### ISSUE TITLE
getting "libpython3.8.so.1.0 cannot open shared object file: No such file or directory" error while running deepstream.py

### ISSUE THREAD

**Issue by ahmedmuzammilAI** [marcoslucianops/DeepStream-Yolo-Face#5]
```
deepstream.py", line 13, in <module>
    import pyds
ImportError: libpython3.8.so.1.0: cannot open shared object file: No such file or directory

```
can you please help me solve this issue! I have python 3.10 install and i dont know why its trying to find python 3.8

**Comment by marcoslucianops** [comment]
Probably, you installed a different `pyds` (deepstream_python_apps) version compared to the DeepStream SDK version.

**Comment by ahmedmuzammilAI** [comment]
thanks! I uninstall and reinstall pyds using "pip install pyds" command and im getting this error:
is there any other way i should install pyds with GPU support? can you please let me know if there is..
```
Traceback (most recent call last):
  File "/opt/nvidia/deepstream/deepstream-6.4/sources/apps/sample_apps/deepstream-face/DeepStream-Yolo-Face-master/deepstream.py", line 401, in <module>
    sys.exit(main())
  File "/opt/nvidia/deepstream/deepstream-6.4/sources/apps/sample_apps/deepstream-face/DeepStream-Yolo-Face-master/deepstream.py", line 309, in main
    osd.set_property('process-mode', int(pyds.MODE_GPU))
AttributeError: module 'pyds' has no attribute 'MODE_GPU'
```

**Comment by marcoslucianops** [comment]
What is your DeepStream version?

**Comment by ahmedmuzammilAI** [comment]
It's 6.4
Thanks I solved that issue by installing pyds using this command:
```
wget https://github.com/NVIDIA-AI-IOT/deepstream_python_apps/releases/download/v1.1.10/pyds-1.1.10-py3-none-linux_x86_64.whl

pip3 install pyds-1.1.10-py3-none-linux_x86_64.whl

```
then I gave the onnx weights and the engine was built successfully but the video gets stuck while opening and it gives segmentation fault(core dumped) error. Please if you could help with this..
is this because of a different deepstream version?

**Comment by marcoslucianops** [comment]
Are you using the correct exporter file in the `utils` folder (from this repo)?

**Comment by ahmedmuzammilAI** [comment]
no sorry! let me check that..

**Comment by ahmedmuzammilAI** [comment]
Hi @marcoslucianops!! Thanks a lot for your help all along the way you're really awesome! I'm able to run it now and detect faces.
I had a few questions if you could please tell me regarding this:
1) will I be able to run this on multiple streams parallelly?
2) can I recognise individual faces with labels/names separately?

**Comment by marcoslucianops** [comment]
You need to do changes in the code to run multiple cameras and recognize individual faces.
